# version: '3'
# services:
#     postgres: [...]
#     redis: [...]
#     nginx: [...]
#     api:
#     depends_on:
#             - postgres
# build: [...]
# volumes: [...]
# environment: [...]
# client: [...]
# worker:
#         build: [...]
#         volumes: [...]
#         environment:
#             - REDIS_HOST=redis
#             - REDIS_PORT=6379
#             - PGUSER=postgres
#             - PGHOST=postgres
#             - PGDATABASE=postgres
#             - PGPASSWORD=postgres_password
#             - PGPORT=5432

version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=simple_blog_api
  api:
    depends_on:
      - postgres
    image: axelsilverdew/simple-api:latest
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
